version: "3.8"

services:
  frontend:
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    environment:
      GO_ENV: production
      PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      VAPID_EMAIL_ADDRESS: ${VAPID_EMAIL_ADDRESS}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
    expose:
      - "8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
