ALTER TABLE push_subscriptions 
ADD COLUMN endpoint TEXT UNIQUE NOT NULL,
ADD COLUMN p256dh_key TEXT NOT NULL,
ADD COLUMN auth_key TEXT NOT NULL,
ADD COLUMN device_name VARCHAR(255) NOT NULL,
ADD COLUMN browser TEXT NOT NULL,
ADD COLUMN platform TEXT NOT NULL,
ADD COLUMN last_used TIMESTAMPTZ
;
